name: Deploy Website
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  Cache-Dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.nvm
          key: testing-cache-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        run: npm ci
  
  Run-Test:
    needs: Cache-Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.nvm
          key: testing-cache-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        run: npm ci
      - name: Test Code
        run: npm run test

  Build-Website:
    needs: Run-Test
    runs-on: ubuntu-latest
    outputs:
      script-file-name: ${{ steps.publish-name.outputs.script-file-name }}
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.nvm
          key: testing-cache-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        run: npm ci
      - name: Build Website
        run: npm run build
      - name: Publish JS name
        id: publish-name
        run: find dist/assets/*.js -type f -execdir echo 'script-file-name={}' >> $GITHUB_OUTPUT ';'
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: transpiled-files
          path: dist

  Deploy-Website:
    needs: Build-Website
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: transpiled-files
      - name: Display Contents
        run: ls
      - name: Output Filename
        run: echo "${{ needs.Build-Website.outputs.script-file-name }}"
      - name: Deploy
        run: echo "Deploying..."
